# Generated by Django 3.2.5 on 2021-07-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyprofile',
            old_name='CyRes_bio',
            new_name='CyRes_Bio',
        ),
        migrations.RenameField(
            model_name='cyprofile',
            old_name='CyRes_start_date',
            new_name='CyRes_Start_Date',
        ),
        migrations.RemoveField(
            model_name='cyprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='cyprofile',
            name='CyRes_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='cyprofile',
            name='CyRes_UserName',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='customerProfile',
            fields=[
                ('CuRes_Org_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('CuRes_Contact_Person', models.CharField(blank=True, max_length=225, null=True)),
                ('CuRes_Contact_Designation', models.CharField(blank=True, max_length=225, null=True)),
                ('CuRes_Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('CuRes_Phone', models.TextField(blank=True, null=True)),
                ('CuRes_Profile_Image', models.ImageField(blank=True, default='Profile_Icon.png', null=True, upload_to='')),
                ('CuRes_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('CuRes_organization_Sector', models.CharField(blank=True, max_length=500, null=True)),
                ('CuRes_Start_Date', models.CharField(blank=True, max_length=500, null=True)),
                ('CuRes_Documents', models.CharField(blank=True, max_length=500, null=True)),
                ('CuRes_Created', models.DateTimeField(auto_now_add=True)),
                ('CuRes_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('CuRes_User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
