# Generated by Django 3.2.5 on 2021-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210720_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='CuRes_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='CuRes_Documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='CuRes_Phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='CuRes_organization_Sector',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Priavte', 'Priavte')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='cyprofile',
            name='CyRes_Documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cyprofile',
            name='CyRes_Service_Type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Priavte', 'Priavte'), ('Both', 'Both')], max_length=225, null=True),
        ),
    ]
