# Generated by Django 3.2.5 on 2021-07-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyprofile',
            old_name='CyRes_User',
            new_name='user',
        ),
    ]
