# Generated by Django 3.2.5 on 2021-07-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_cyres_user_cyprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='CuRes_User',
            new_name='user',
        ),
    ]
