# Generated by Django 3.2.5 on 2021-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cures_user_customerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='CuRes_Status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='cyprofile',
            name='CuRes_Status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
    ]
