# Generated by Django 3.2.5 on 2021-07-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210726_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='CuRes_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='cyprofile',
            name='CyRes_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
