# Generated by Django 3.2.5 on 2021-09-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cy_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cy_logs',
            name='CyRes_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cyprofile'),
        ),
    ]
