# Generated by Django 3.2.5 on 2021-09-11 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_cy_logs_cyres_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyprofile',
            name='CyRes_Created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 11, 18, 42, 3, 657846, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
