# Generated by Django 3.2.5 on 2021-07-20 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('SRA_Organization_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('CyRes_UserName', models.CharField(blank=True, max_length=225, null=True)),
                ('SRA_Danger_Of_Vuln', models.CharField(blank=True, max_length=225, null=True)),
                ('CyRes_ID', models.CharField(blank=True, max_length=225, null=True)),
                ('SRA_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SRA_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Request',
            fields=[
                ('SR_Organization_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_Type', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_URL', models.CharField(blank=True, max_length=5000, null=True)),
                ('SR_Approval_status', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_Description', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_Low_Award', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_Medium_Award', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_High_Award', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_Critical_Award', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_ID', models.CharField(blank=True, max_length=225, null=True)),
                ('CReg_ID', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SR_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services_Request_Participant',
            fields=[
                ('SRP_Organization_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_Services_Type', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_Report', models.FileField(blank=True, null=True, upload_to='')),
                ('SRP_Status', models.CharField(blank=True, max_length=225, null=True)),
                ('SR_ID', models.CharField(blank=True, max_length=225, null=True)),
                ('CyRes_ID', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SRP_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
