# Generated by Django 3.2.5 on 2021-07-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services_Request',
            new_name='ServicesRequest',
        ),
        migrations.RenameModel(
            old_name='Services_Request_Participant',
            new_name='ServicesRequestParticipant',
        ),
    ]
