# Generated by Django 3.2.5 on 2021-07-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_2122'),
        ('services', '0002_auto_20210720_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrequest',
            name='CReg_ID',
        ),
        migrations.RemoveField(
            model_name='servicesrequest',
            name='SRP_ID',
        ),
        migrations.AddField(
            model_name='servicesrequest',
            name='CuRes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='CyRes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cyprofile'),
        ),
        migrations.AlterField(
            model_name='servicesrequest',
            name='SR_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesrequest',
            name='SR_URL',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='servicesrequestparticipant',
            name='CyRes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cyprofile'),
        ),
        migrations.AlterField(
            model_name='servicesrequestparticipant',
            name='SR_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequest'),
        ),
    ]
