# Generated by Django 3.2.5 on 2021-07-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210720_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='CyRes_ID',
        ),
        migrations.RemoveField(
            model_name='servicesrequest',
            name='CuRes_ID',
        ),
        migrations.RemoveField(
            model_name='servicesrequestparticipant',
            name='CyRes_ID',
        ),
        migrations.RemoveField(
            model_name='servicesrequestparticipant',
            name='SR_ID',
        ),
    ]
