# Generated by Django 3.2.5 on 2021-07-20 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_2122'),
        ('services', '0004_auto_20210720_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='CyRes_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cyprofile'),
        ),
        migrations.AddField(
            model_name='servicesrequest',
            name='CuRes_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='CyRes_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cyprofile'),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SR_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequest'),
        ),
    ]
