# Generated by Django 3.2.5 on 2021-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210720_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesrequest',
            name='SR_Approval_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Witing_for_Pyament', 'Witing for Pyament'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
    ]
