# Generated by Django 3.2.5 on 2021-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_awards_sra_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='SRA_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequest',
            name='SR_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
