# Generated by Django 3.2.5 on 2021-08-01 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210727_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesrequestparticipant',
            name='SRP_Status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='SR_LOGS',
            fields=[
                ('SR_LOG_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SRA_Created', models.DateTimeField(auto_now_add=True)),
                ('SR_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequest')),
            ],
        ),
    ]
