# Generated by Django 3.2.5 on 2021-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210801_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr_logs',
            name='SR_LOG_Status',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
