# Generated by Django 3.2.5 on 2021-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_sr_logs_sr_log_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr_logs',
            name='SR_LOG_User',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
