# Generated by Django 3.2.5 on 2021-08-02 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_sr_logs_sr_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRP_LOGS',
            fields=[
                ('SRP_LOG_Status', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_LOG_User', models.CharField(blank=True, max_length=225, null=True)),
                ('SRP_LOG_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SRP_Created', models.DateTimeField(auto_now_add=True)),
                ('SRP_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequest')),
            ],
        ),
    ]
