# Generated by Django 3.2.5 on 2021-08-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_srp_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srp_logs',
            name='SRP_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequestparticipant'),
        ),
    ]
