# Generated by Django 3.2.5 on 2021-08-03 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_awards_sra_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Bug',
            fields=[
                ('Re_UserName', models.CharField(blank=True, max_length=225, null=True)),
                ('Re_Phone', models.CharField(blank=True, max_length=225, null=True)),
                ('Re_Email', models.CharField(blank=True, max_length=225, null=True)),
                ('Re_Title', models.CharField(blank=True, max_length=225, null=True)),
                ('Re_Description', models.TextField(blank=True, null=True)),
                ('Re_Report', models.FileField(blank=True, null=True, upload_to='')),
                ('Re_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SRP_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
