# Generated by Django 3.2.5 on 2021-08-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_report_bug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_bug',
            old_name='SRP_Created',
            new_name='Re_Created',
        ),
    ]
