# Generated by Django 3.2.5 on 2021-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_rename_srp_created_report_bug_re_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_bug',
            name='Re_Status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=225, null=True),
        ),
    ]
