# Generated by Django 3.2.5 on 2021-08-04 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_report_bug_cyres_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReBug_LOGS',
            fields=[
                ('ReBug_LOG_Status', models.CharField(blank=True, max_length=225, null=True)),
                ('ReBug_LOG_User', models.CharField(blank=True, max_length=225, null=True)),
                ('ReBug_LOG_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ReBug_Created', models.DateTimeField(auto_now_add=True)),
                ('ReBug_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicesrequestparticipant')),
            ],
        ),
    ]
