# Generated by Django 3.2.5 on 2021-08-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_rebug_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebug_logs',
            name='ReBug_ID',
        ),
        migrations.AddField(
            model_name='rebug_logs',
            name='Re_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.report_bug'),
        ),
    ]
