# Generated by Django 3.2.5 on 2021-08-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20210804_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
