# Generated by Django 3.2.5 on 2021-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_auto_20210815_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Loss_of_Accountability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Loss_of_Availability',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Loss_of_Confidentiality',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Loss_of_Integrity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Total',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
