# Generated by Django 3.2.5 on 2021-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20210904_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='srp_logs',
            name='SRA_Loss_of_Accountability',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='srp_logs',
            name='SRA_Loss_of_Availability',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='srp_logs',
            name='SRA_Loss_of_Confidentiality',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='srp_logs',
            name='SRA_Loss_of_Integrity',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='srp_logs',
            name='SRA_Technical_Total',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
