# Generated by Django 3.2.5 on 2021-09-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20210904_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='srp_logs',
            name='SRP_Note',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
