# Generated by Django 3.2.5 on 2021-09-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_srp_logs_srp_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesrequestparticipant',
            name='SRP_Danger',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
