# Generated by Django 3.2.5 on 2021-09-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_servicesrequestparticipant_srp_danger'),
    ]

    operations = [
        migrations.AddField(
            model_name='srp_logs',
            name='SRP_LOG_Danger',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
